//! Universal Config Exporter trait and concrete implementations for terminal synchronization.

use crate::backend::error::AppError;
use std::future::Future;
use std::path::Path;
use std::pin::Pin;

/// Trait for universal theme synchronization across desktop environment apps.
pub trait ThemeExporter: Send + Sync {
    fn name(&self) -> &'static str;
    fn export<'a>(
        &'a self,
        shades: &'a [[u8; 3]],
    ) -> Pin<Box<dyn Future<Output = Result<(), AppError>> + Send + 'a>>;
}

pub struct AlacrittyExporter;

impl ThemeExporter for AlacrittyExporter {
    fn name(&self) -> &'static str {
        "Alacritty"
    }

    fn export<'a>(
        &'a self,
        shades: &'a [[u8; 3]],
    ) -> Pin<Box<dyn Future<Output = Result<(), AppError>> + Send + 'a>> {
        Box::pin(async move {
            let home = std::env::var("HOME")
                .map_err(|_| AppError::Io("Could not resolve $HOME".to_string()))?;
            let dir = Path::new(&home).join(".config").join("alacritty");
            if !dir.exists() {
                tokio::fs::create_dir_all(&dir).await?;
            }
            let file_path = dir.join("alacritty.toml");

            let mut toml_content = String::from("# Automatically generated by wallmod Theme Exporter\n[colors.primary]\nbackground = \"#09090b\"\nforeground = \"#fafafa\"\n\n[colors.normal]\n");
            let names = [
                "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
            ];
            for (i, name) in names.iter().enumerate() {
                let rgb = shades.get(i % shades.len()).unwrap_or(&[128, 128, 128]);
                toml_content.push_str(&format!(
                    "{} = \"#{:02x}{:02x}{:02x}\"\n",
                    name, rgb[0], rgb[1], rgb[2]
                ));
            }

            tokio::fs::write(&file_path, toml_content).await?;
            Ok(())
        })
    }
}

pub struct KittyExporter;

impl ThemeExporter for KittyExporter {
    fn name(&self) -> &'static str {
        "Kitty"
    }

    fn export<'a>(
        &'a self,
        shades: &'a [[u8; 3]],
    ) -> Pin<Box<dyn Future<Output = Result<(), AppError>> + Send + 'a>> {
        Box::pin(async move {
            let home = std::env::var("HOME")
                .map_err(|_| AppError::Io("Could not resolve $HOME".to_string()))?;
            let dir = Path::new(&home).join(".config").join("kitty");
            if !dir.exists() {
                tokio::fs::create_dir_all(&dir).await?;
            }
            let file_path = dir.join("kitty.conf");

            let mut conf_content = String::from("# Automatically generated by wallmod Theme Exporter\nbackground #09090b\nforeground #fafafa\n");
            for i in 0..8 {
                let rgb = shades.get(i % shades.len()).unwrap_or(&[128, 128, 128]);
                conf_content.push_str(&format!(
                    "color{} #{:02x}{:02x}{:02x}\n",
                    i, rgb[0], rgb[1], rgb[2]
                ));
            }

            tokio::fs::write(&file_path, conf_content).await?;
            Ok(())
        })
    }
}
